version: '3.7'

services:

  shortener:
      container_name: shortener
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - LOGSTASH_HOST=logstash
        - LOGSTASH_PORT=5044
      depends_on:
        - redis

  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - redis:/data
volumes:
  redis: